#SPDX-License-Identifier: MIT-0
---
# tasks file for add-versions
- name: Create version report directory
  file:
    path: /opt/software-versions
    state: directory
    mode: '0755'
    owner: root
    group: root


# Get versions info 

- name: Get Sublime Text version
  command: subl --version
  register: sublime_version
  changed_when: false
  ignore_errors: yes

- name: Get Jenkins version
  command: jenkins --version
  register: jenkins_version
  changed_when: false
  ignore_errors: yes

- name: Get Python 3.14 version
  command: /usr/local/bin/python3.14 --version
  register: python_version
  changed_when: false
  ignore_errors: yes

- name: Get Chrome version
  command: google-chrome --version
  register: chrome_version
  changed_when: false
  ignore_errors: yes

- name: Get Notepad++ version 
  command: snap info notepad-plus-plus
  register: notepadpp_version
  changed_when: false
  ignore_errors: yes


- name: Parse Notepad++ version
  set_fact:
    notepadpp_ver: >-
      {{ notepadpp_version.stdout_lines
         | select('match', '^installed:')
         | first
         | default('Notepad++: Not installed') }}
  when: notepadpp_version.rc == 0
  ignore_errors: yes

# Writing versions to file
- name: Write software versions to file
  copy:
    dest: /opt/software-versions/versions.txt
    mode: '0644'
    content: |
      
      Software Version Report :=
      ------------------------
      1. Sublime Text
         {{ sublime_version.stdout | default('Not installed or not found') }}

      2. Jenkins
         {{ jenkins_version.stdout | default('Not installed or not found') }}

      3. Python
         {{ python_version.stdout | default('Not installed or not found') }}

      4. Google Chrome
         {{ chrome_version.stdout | default('Not installed or not found') | trim }}

      5. Notepad++
         {{ notepadpp_ver | default('Not installed or not found') | trim }}


- name: Display version report
  command: cat /opt/software-versions/versions.txt
  register: report_output
  changed_when: false

- name: Show report contents
  debug:
    var: report_output.stdout_lines

